### ISSUE TITLE
Please, mark this as question. Is this board OTA compatible.

### ISSUE THREAD

**Issue by woodlist** [easytarget/esp32-cam-webserver#101]
I have tried to get OTA worked, but that was not successful. Truly said, I started from most sophisticated way, through SSL layer, via GSM connection, from WEB hosted firmware. The photo sending to same server via GSM on secure protocol was okay. The OTA falls.

**Comment by easytarget** [comment]
No.
This firmware is not currently (v3.x) OTA compatible. The face recognition code makes it too large to allow OTA. See #4
