### ISSUE TITLE
add sensor values or other dynamic  info to the image or to the html page

### ISSUE THREAD

**Issue by jasza2** [easytarget/esp32-cam-webserver#113]
I intend to use this as a general user interface for other sensors e.g. door open/close sensor, temperature, distance etc. I would like to display this information to the user alongside (or over) the video stream.

I can modify the HTML directly with static information that appears at the top under the buttons but how do I make this dynamic sensor information? 

I also tried inserting it onto the image like on line 225 of app_httpd.cpp but it had no effect. 
  `rgb_printf(image_matrix, FACE_COLOR_CYAN, "ID[%u] Sample[%u]", this_face, ENROLL_CONFIRM_TIMES - left_sample_face);`
          
Either of these two methods would work for me, some pointers as to how to modify the code would be great thanks!!!

**Comment by easytarget** [comment]
Dup of #114
