### ISSUE TITLE
MotionEye not a supported network camera

### ISSUE THREAD

**Issue by jannikb16** [easytarget/esp32-cam-webserver#127]
The title is my problem xD
I cannot integrate the camera in MotionEye.
It works with the original ESP Cam web server but not with your cool version.
![mhhh](https://user-images.githubusercontent.com/45617754/123471422-0f484e00-d5f6-11eb-85f4-86f6c9120cd6.png)

**Comment by jannikb16** [comment]
FIXED
-
I had to remove /view.
Only the ip and port like 8.8.8.8:81 
-
#57

**Comment by easytarget** [comment]
I'm glad you got that fixed, thanks for updating the issue and closing it :tada:
