### ISSUE TITLE
Add upload still picture to Google Drive

### ISSUE THREAD

**Issue by chupocro** [easytarget/esp32-cam-webserver#136]
Hi,

I was experimenting with a separate firmware for uploading still images to Google Drive based on [this code](https://github.com/fustyles/Arduino/tree/master/ESP32-CAM_SD_GoogleDrive) and then I tried to combine it with the webserver code but I still didn't solve a problem with the following error:

`start_ssl_client(): Free internal heap before xxxxxx`

Maybe you could try to incorporate the function to upload every captured still image to Google Drive? That would be a nice function.

I am assuming the problem is using **esp_http_server** and **WiFiClientSecure** in the same time and it should be possible to wait for **httpd_resp_send()** to finish sending the response and to then free the heap before using **WiFiClientSecure** but I am still looking for a way how that could be done.

Or maybe there is even a way of using **esp_http_server** only because the function:

`client_tcp.setInsecure();`

has to be used for the code to work with **WiFiClientSecure**.

Regards

**Comment by easytarget** [comment]
Thank you for the suggestions!

Adding `https:` support is covered by #54 , it's something I'd like to do but is not entirely easy, and will only get worked on by me if I get the time and energy to do it, or someone else does that and submits a working PR.

I'm not adding integrations to other services, as I said in #99 I want to keep this project focused on being a nice example of a browser based webcam. This request is rather out-of-scope, there are probably other esp-cam firmwares that are better suited for your needs.
