### ISSUE TITLE
Two code suggestions for M5STACK compatibility and notification LED disabling

### ISSUE THREAD

**Issue by tobiasisenberg** [easytarget/esp32-cam-webserver#138]
Sorry, a pull request would probably be the right approach, but I am not very used to creating them, so here are two simple suggestions for improvement, both for ```esp32-cam-webserver.ino```.

First, when one uses ```CAMERA_MODEL_M5STACK_ESP32CAM``` (and probably other models) the code does not compile. The reason is this code section:
```
    // Initialise and set the lamp
    if (lampVal != -1) {
        ledcSetup(lampChannel, pwmfreq, pwmresolution);  // configure LED PWM channel
        if (autoLamp) setLamp(0);                        // set default value
        else setLamp(lampVal);
        ledcAttachPin(LAMP_PIN, lampChannel);            // attach the GPIO pin to the channel
    } else {
        Serial.println("No lamp, or lamp disabled in config");
    }
```
because ```LAMP_PIN``` is not defined for ```CAMERA_MODEL_M5STACK_ESP32CAM```. The respective code section would never be called because ```lampVal``` is set correctly due to ```LAMP_PIN``` not existing, but this is a parser issue at compile time. I propose to catch this problem with a simple ```#ifdef``` as follows:
```
    // Initialise and set the lamp
    if (lampVal != -1) {
        ledcSetup(lampChannel, pwmfreq, pwmresolution);  // configure LED PWM channel
        if (autoLamp) setLamp(0);                        // set default value
        else setLamp(lampVal);
#ifdef LAMP_PIN
        ledcAttachPin(LAMP_PIN, lampChannel);            // attach the GPIO pin to the channel
#endif
    } else {
        Serial.println("No lamp, or lamp disabled in config");
    }
```

Second, in situations when one defines ```LAMP_DISABLE``` one probably also does not want the notification LED to be on (e.g., for using the camera to observe animals such as in a bird house). So either provide an additional define for disabling the notification LED explicitly and act upon it, or re-use the ```LAMP_DISABLE``` one as follows, right after the ```#include "camera_pins.h"```:
```
// Pin Mappings
#include "camera_pins.h"

#ifdef LAMP_DISABLE // in that case also disable notification LED
  #undef LED_PIN
  #undef LED_ON
  #undef LED_OFF
#endif
```

I hope this helps, and it should be straightforward to include into the code base.

**Comment by easytarget** [comment]
Thanks for the report, sorry it took some time to get to it.
I've fixed the compile issue as you suggested, and added a config setting so the user can decide what combo of lamp and notification led's they want.
