### ISSUE TITLE
add ESP32 temperature to GUI

### ISSUE THREAD

**Issue by TungstenE2** [easytarget/esp32-cam-webserver#151]
Tasmota implemented ESP32 temperatue reading to GUI.

Is this possible to add this value to esp32-cam-webserver GUI as well?

![grafik](https://user-images.githubusercontent.com/39955685/127463089-c578a557-30f3-432d-a2ff-0d149db4f3e4.png)

**Comment by haraldtux** [comment]
maybe like this (MCU temperature :....) :
![IMG_20210808_155014A](https://user-images.githubusercontent.com/39169481/128634581-7c3d800d-6024-4f22-b26e-6abc0ea0c5b2.jpg)
In file : app_httpd.cpp
line 78 to add :
// the_hara 
#ifdef __cplusplus
extern "C" {
#endif
uint8_t temprature_sens_read();
#ifdef __cplusplus
}
#endif
uint8_t temprature_sens_read();
// the_hara 

line 560 to add :
//the_hara 
    int McuTc = (temprature_sens_read() - 32) / 1.8; // celsius
    int McuTf = temprature_sens_read(); // fahrenheit
    d+= sprintf(d,"MCU temperature : %i *C, %i *F<br>\n", McuTc, McuTf); 
//the_hara

**Comment by easytarget** [comment]
I've already discussed and decided not to do this.
The temp sensor is not part of the cheap ESP32S1 chips most of the AI-Thinker clones are based upon. It certainly is not present in any of mine; I have tested them. See https://github.com/espressif/arduino-esp32/issues/2422
Also, dup. of #56

**Comment by TungstenE2** [comment]
To be honest, this is a petty. On my cams this is working great and also Tasmota is offering this. Why not add it to the dump page? If the sensor is not present just no value is shown, but it gives more details and in my case very usefull as well.

Please reconsider. Thx

![grafik](https://user-images.githubusercontent.com/39955685/130398384-b6ff11c9-550a-408f-9d6e-584497e72dbc.png)

**Comment by easytarget** [comment]
You are, of course, quite right. I'll see what I can do since adding this (if available) to the data page is trivial

**Comment by mrneutron42** [comment]
How do we turn on the temperature reading in the GUI?
I've got Tasmota ESP32-CAM 12.5.0.3 loaded and it's only showing framerate in the GUI.
![ESP32-CAM GUI main 12 5 0 3](https://github.com/easytarget/esp32-cam-webserver/assets/70338169/291a8008-999c-41f4-a028-2240baa73439)
