### ISSUE TITLE
stream gets blurry caused by high temperature

### ISSUE THREAD

**Issue by TungstenE2** [easytarget/esp32-cam-webserver#152]
I have a cam set up in a bird nesting house. During the cause of the day the stream gets blurry/washed and fine again in late afternoon.

Not sure if this is related to temperature or sun radiation. Anybody else discovered this and may be a fix?

![grafik](https://user-images.githubusercontent.com/39955685/127476399-207d1ff1-5ab6-463d-87cf-edb97ecdcf74.png)

![grafik](https://user-images.githubusercontent.com/39955685/127476472-8773dec3-0a3a-4003-b253-57261cb02901.png)

**Comment by TungstenE2** [comment]
I was able to monitor the temperatur as suggested here https://github.com/easytarget/esp32-cam-webserver/issues/151

In 3d printed housing with lamp at 90% I see even on a cloudy day with outside temperature of 24 C over 90 C on ESP32.

![grafik](https://user-images.githubusercontent.com/39955685/128697674-582bd8d3-2858-4aca-bace-dd62993a6b90.png)

**Comment by easytarget** [comment]
I'm afraid there is nothing I can really do here, beyond suggesting some sort of cooing, I added a Heatsink(*) to the ESP32 that runs my CNC just to be on the safe side.

But blurring in the camera is probably condensation or some side-effect from the CCD array. Exacerbated by being cose to the MCU. Maybe the camera module itself can be moved away or insulated from the ESP32 itself?

(*) Small one intended for RasPi cpu, directly bonded with thermal glue.

**Comment by easytarget** [comment]
There is now, at least, a temperature feedback on  the info page.
