### ISSUE TITLE
Add reboot-timer to AP mode

### ISSUE THREAD

**Issue by 5A52** [easytarget/esp32-cam-webserver#157]
Hi, thanks foe your work.
Please add reboot-timer to AP mode. If for any reason camera is booted to AP mode (example:router not ready yet) it stays in AP until manual reboot. So have a reboot-timer will be a good option. For scenarios where cam works always in AP it is possible to set this timer to 0.

**Comment by easytarget** [comment]
I understand your problem, but feel it is a solution in search of a problem, certainly in an example sketch like this.
When AP mode is configured as a fallback and it becomes active you can connect to the AP and send a reboot from the button in the UI . If you do not need fallback functionality you can disable it in the config.
Feel free to code this properly (eg with config and documentation) and submit a PR, but it's not something I will be working on.
