### ISSUE TITLE
ERROR: E (1099) SPIFFS: mount failed, -10025

### ISSUE THREAD

**Issue by coolduke666** [easytarget/esp32-cam-webserver#175]
using the latest beta 4.x - setting up all according to the documentation - flashed with arduino without any issue... (double checked the partition theme and PSRAM setting... the but doesnt startup:

11:37:04.987 -> ====
11:37:04.987 -> esp32-cam-webserver: ESP32 camera server
11:37:04.987 -> Code Built: Oct 18 2021 @ 11:31:30
11:37:04.987 -> Base Release: 4.0.beta2
11:37:05.174 -> Camera init succeeded
11:37:05.174 -> OV2640 camera module detected
11:37:05.221 -> E (1099) SPIFFS: mount failed, -10025
11:37:06.163 -> ets Jun  8 2016 00:22:57
11:37:06.163 -> 
11:37:06.163 -> rst:0x8 (TG1WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
11:37:06.210 -> configsip: 0, SPIWP:0xee
11:37:06.210 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
11:37:06.210 -> mode:DIO, clock div:1
11:37:06.210 -> load:0x3fff0030,len:1240
11:37:06.210 -> load:0x40078000,len:13012
11:37:06.210 -> load:0x40080400,len:3648
11:37:06.210 -> entry 0x400805f8

any help appreciated :)
thx

**Comment by founfabug** [comment]
Another solution of sorts. I can confirm that timing is the issue with respect to **4.0.beta2** the execution of the format function in `filesystemStart()` in `storage.cpp` is not effective with my board. A `Serial.println` and delay of 250 just prior to :
    `Serial.println("If it happens repeatedly check if a SPIFFS partition is present for your board?");`
was sufficient to allow the format to complete with success. After this, the delay was not needed.

Saving and Loading of preferences works, and the webcam software is a joy compared to the espressif demo, thank you.

Thinking about why this should happen, as there is already a delay of 1000 in this function, I suspect the `flashLED(100)` instruction may be involved?

**Comment by coolduke666** [comment]
Nice. Will there be a bugfix in the next beta? Release date? Thx

**Comment by easytarget** [comment]
Interesting.. I'll look at the timings and see what can be done. Thanks for the reports guys!

**Comment by skorokithakis** [comment]
I keep having this issue, regardless of the workarounds in the thread. I have what appears to be an AI-thinker module, but who really knows? Currently the code is unusable for me, though :(

**Comment by Aquillum** [comment]
I also have this issue, no matter if I put `delay(1000);` as @Dr-InSide mentioned or `delay(2000);` 
Default Webcam-Example Sketch runs fine

```
esp32-cam-webserver: HARRY ESP32 CAM 060122
Code Built: Jan 11 2022 @ 10:33:23
Base Release: 4.0.beta3
Camera init succeeded
OV2640 camera module detected
E (3103) SPIFFS: mount failed, -10025
ets Jun  8 2016 00:22:57

rst:0x8 (TG1WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1324
ho 0 tail 12 room 4
load:0x40078000,len:13508
load:0x40080400,len:3604
entry 0x400805f0

====
esp32-cam-webserver: HARRY ESP32 CAM 060122
Code Built: Jan 11 2022 @ 10:33:23
Base Release: 4.0.beta3
Camera init succeeded
OV2640 camera module detected
E (3103) SPIFFS: mount failed, -10025
```

**Comment by Aquillum** [comment]
**Update:**
I flashed the `SPIFFS_Test.ino` from Eample-Library. Test result OK, takes a while !
Then flashed `esp32-cam-webserver` with same settings as before --> now it starts !

Please test this procedure if you have problems with SPIFFS mount error.

**Comment by remy33** [comment]
The working "solution" I ended up with is to downgrade back to esp32 V1.06.
Keep in mind it won't work with alpha3, sadly.

**Comment by pbenaim** [comment]
> **Update:** I flashed the `SPIFFS_Test.ino` from Eample-Library. Test result OK, takes a while ! Then flashed `esp32-cam-webserver` with same settings as before --> now it starts !
> 
> ```
> esp32-cam-webserver: HARRY ESP32 CAM 060122
> Code Built: Jan 11 2022 @ 22:14:25
> Base Release: 4.0.beta3
> Camera init succeeded
> OV2640 camera module detected
> Internal filesystem contents
> Listing SPIFFS directory: /
> Preference file /esp32cam-preferences.json not found; using system defaults.
> Lamp: 0%, pwm = 0
> Starting WiFi
> ```
> 
> Please test this procedure if you have problems with SPIFFS mount error.
> 
> **Update:** The module works but as soon as i hit `Save `i get a Boot Loop:
> 
> ```
> ====
> esp32-cam-webserver: HARRY ESP32 CAM 060122
> Code Built: Jan 11 2022 @ 23:06:41
> Base Release: 4.0.beta3
> Camera init succeeded
> OV2640 camera module detected
> ets Jun  8 2016 00:22:57
> 
> rst:0x8 (TG1WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0xee
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:1
> load:0x3fff0030,len:1324
> ho 0 tail 12 room 4
> load:0x40078000,len:13508
> load:0x40080400,len:3604
> entry 0x400805f0
> 
> ====
> ```
> 
> This can only be resolved with the SPIFFS_Test.ino procedure. A new flash withou that brings again the SPIFFS mount error....

Work after format the SPIFFS ;-)

bool formatted = SPIFFS.format();

if(formatted){
    Serial.println("\n\nSuccess formatting");
}else{
    Serial.println("\n\nError formatting");
}

**Comment by Aquillum** [comment]
> Work after format the SPIFFS ;-)
> 
> bool formatted = SPIFFS.format();
> 
> if(formatted){
> Serial.println("\n\nSuccess formatting");
> }else{
> Serial.println("\n\nError formatting");
> }

Thank you, I will try this.

At what exact line in which file should this block be inserted ?

**Comment by pbenaim** [comment]
> > Work after format the SPIFFS ;-)
> > bool formatted = SPIFFS.format();
> > if(formatted){
> > Serial.println("\n\nSuccess formatting");
> > }else{
> > Serial.println("\n\nError formatting");
> > }
> 
> Thank you, I will try this.
> 
> At what exact line in which file should this block be inserted ?

In setup of SPIFFS_Test.ino after Serial.begin(115200);
    if(!SPIFFS.begin(FORMAT_SPIFFS_IF_FAILED)){
        Serial.println("SPIFFS Mount Failed");
        return;
    }

and delete other things

But, the better way, it's  make just one ino project to only format SPIFFS..

**Comment by fryzjeruch26** [comment]
> I flashed the SPIFFS_Test.ino from Eample-Library. Test result OK, takes a while !

I follow this steps but when I try to save the settings camera crashes.
The working solution for me was as follows:
in **setup()** of esp32-cam-webserver.ino I moved **Delay(200);** between **filesystemStart();** and **loadPrefs(SPIFFS);**
like this:

> if (filesystem) { 
>             filesystemStart();
>             delay(200); // a short delay to let spi bus settle after camera init
>             loadPrefs(SPIFFS);
>         } else {
>             Serial.println("No Internal Filesystem, cannot load or save preferences");
>         }
>     }
and everything start works perfect ! I can save the config 

I have one more camera from the same amazon seller, so I'm gonna test this without flashing  **SPIFFS_Test.ino**  and just moving the **delay();** and see, then I'll update the results here :)

**Comment by Aquillum** [comment]
> > I flashed the SPIFFS_Test.ino from Eample-Library. Test result OK, takes a while !
> 
> I follow this steps but when I try to save the settings camera crashes. The working solution for me was as follows: in **setup()** of esp32-cam-webserver.ino I moved **Delay(200);** between **filesystemStart();** and **loadPrefs(SPIFFS);** like this:
> 
> > if (filesystem) {
> > filesystemStart();
> > delay(200); // a short delay to let spi bus settle after camera init
> > loadPrefs(SPIFFS);
> > } else {
> > Serial.println("No Internal Filesystem, cannot load or save preferences");
> > }
> > }
> 
> I can save the config, erase then change and save again. Everything works perfect !
> 
> I have one more camera from the same amazon seller, so I'm gonna test this without flashing **SPIFFS_Test.ino** and just moving the **delay();** and see, then I'll update the results here :)

I tried to compile and flash with the delay200) on a brand new ESP32-CAM but I got SPIFFS Error at boot.
I then flashesd the Format_SPIFFS.ino -->" Success formatting."
Then again esp32-cam-webserver and I also can Save the config. 
It seems formattingt SPIFFS is mandatory.

**Comment by pauljurczak** [comment]
I have the same problem. Where can I find `Format_SPIFFS.ino`? I cloned https://github.com/espressif/arduino-esp32 and it's not there.

**Comment by pauljurczak** [comment]
Never mind. I found this: https://techtutorialsx.com/2019/02/24/esp32-arduino-formatting-the-spiffs-file-system/

**Comment by JBaczuk** [comment]
> I have the same problem. Where can I find `Format_SPIFFS.ino`? I cloned https://github.com/espressif/arduino-esp32 and it's not there.

I know you found it, but for anyone else, it's in the Arduino IDE, once you install the ESP32 boards, you can go to `File > Examples > SPIFFS > SPIFFS_Test`. Flashing and letting the program write the test file allowed me to then flash the `esp32-cam-webserver` and everything is working now.

**Comment by easytarget** [comment]
Rolling this and all related into a single issue: #214

**Comment by Muplex** [comment]
Hello, even if i successfully format the SPIFFS following the upper instruction, i keep have the boot loop  error with following message

```
esp32-cam-webserver: ESP32 camera server
Code Built: Nov 19 2022 @ 18:05:51
Base Release: 4.0

Starting internal SPIFFS filesystem
Listing SPIFFS directory: /
Camera init succeeded
OV2640 camera module detected
Preference file /esp32cam-preferences.json not found; using system defaults.
Starting WiFi
Known external SSIDs:  'XYZZZ'
MAC address: 24:62:AB:CA:66:5D
Scanning local Wifi Networks
ets Jun  8 2016 00:22:57


rst:0x8 (TG1WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13864
load:0x40080400,len:3608
entry 0x400805f0
```

Have some one fixed in other ways ?
