### ISSUE TITLE
Sketch uses 2783821 bytes (141%) of program storage space. Maximum is 1966080 bytes.

### ISSUE THREAD

**Issue by founfabug** [easytarget/esp32-cam-webserver#176]
With Arduino 1.8.16 on both linux and windows (different installs), "ESP32 Dev Module", "Minimal SPIFFS..." **v3.4** of esp32-cam-webserver reports 
> Sketch uses 2783821 bytes (141%) of program storage space. Maximum is 1966080 bytes.

Board manager url used 
> https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json

Board is an AI Thinker

I tested v4 beta 2 of esp32-cam-webserver and it compiles within available memory for above config, installs, runs, but logs errors about camera initialisation. I'd like to look at that after I have a working baseline for v3.4

Espressif example at https://github.com/espressif/arduino-esp32/tree/master/libraries/ESP32/examples/Camera/CameraWebServer compiles, installs, and functions when configured for AI_THINKER, so the board and tool chain appear Ok.

**Comment by founfabug** [comment]
Thank you very much for your quick attention.

My confusion came from following the default README.md @ https://github.com/easytarget/esp32-cam-webserver.

It has the "ESP32 Dev Module", "Minimal SPIFFS..." requirement and directs :

> Download the latest release of the sketch from https://github.com/easytarget/esp32-cam-webserver/releases/latest

Which points to the 3.4 version software, so I ended up with the wrong setup :-)

Now:

Selecting AI-Thinker' board results in issue #175 
>ERROR: E (1099) SPIFFS: mount failed, -10025

Selecting "ESP32 Dev Module" with "4Mb with SPIFFS" (default) Arduino: 1.8.16 (Linux), Board: "ESP32 Dev Module, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, Core 1, Core 1, None"

> Sketch uses 2783741 bytes (212%) of program storage space. Maximum is 1310720 bytes.

Selecting "ESP32 Dev Module" with "Huge App" compiles, installs and runs with errors:

> esp32-cam-webserver: ESP32 camera server
> Code Built: Oct 22 2021 @ 11:18:14
> Base Release: 3.4
> E (136) cam_hal: cam_dma_config(271): frame buffer malloc failed
> E (136) cam_hal: cam_config(355): cam_dma_config failed
> E (136) camera: Camera config failed with error 0xffffffff
> 
> CRITICAL FAILURE: Camera sensor failed to initialise.

For additional information, I tested with v4.2:

> No PSRAM found.

Then

> esp32-cam-webserver: ESP32 camera server
> Code Built: Oct 22 2021 @ 11:25:29
> Base Release: 4.0.beta2
> E (136) cam_hal: cam_dma_config(271): frame buffer malloc failed
> E (136) cam_hal: cam_config(355): cam_dma_config failed
> E (136) camera: Camera config failed with error 0xffffffff
> CRITICAL FAILURE: Camera sensor failed to initialise.
>

**Comment by tobiasisenberg** [comment]
Same issue here on the camera not being recognized. Because this is a different problem from the initial one, I opened [a new issue](https://github.com/easytarget/esp32-cam-webserver/issues/182).

**Comment by easytarget** [comment]
`E (136) camera: Camera config failed with error 0xffffffff`
https://github.com/espressif/esp-idf/issues/6288

Check your config and ensure PSRAM is enabled, if you still see the sketch saying it has no PSRAM then you have a defective/unsupported board.

I'm thinking that PSRAM is no longer optional for the camera features with the latest expressif IDE cores.

**Comment by easytarget** [comment]
Tested; yep; PSRAM is now a hard requirement. Without it the sketch enters the camera fail loop with:
```
E (165) cam_hal: cam_dma_config(280): frame buffer malloc failed
E (165) cam_hal: cam_config(364): cam_dma_config failed
E (166) camera: Camera config failed with error 0xffffffff
```
So; I'm going to modify the sketch to simply halt if PSRAM is notdetected.

**Comment by easytarget** [comment]
Closing; 
#196 will track the change to fail the code.
