### ISSUE TITLE
esp32cam programming problem 

### ISSUE THREAD

**Issue by Patsjemoe** [easytarget/esp32-cam-webserver#189]
Hi,
My newest esp32cam cannot be programmed , although I do exactly the same as with my other esp32cam module.
I noticed that my latest module has a different esp32 module on board, not from AI Thinker ...but unknown, do not recognise the logo.

I attached a picture of both : 
![esp32camaithinker](https://user-images.githubusercontent.com/51908646/143677722-50e4691b-b5dc-45a7-a974-740fc0440d87.JPG)
![esp32camwhoisthis](https://user-images.githubusercontent.com/51908646/143677724-7783cdce-0e29-4ed6-8a59-83a17f1c99c7.JPG)

Is this a fake device ?
Do I need to select another module then AI Thinker esp32cam ?
I alsready changed to programming module...not better.
any suggestion ?
Regards
Ludo

**Comment by Kallemanni** [comment]
Hey there, I also had different problems with my boards and I have the exact same as the one that you got.
For me it helped to update the ESP32 Core for Arduino IDE to version 1.0.6. ... maybe it will work for you also?
In addition you may try the ESP32 Dev Module and enable the PSRAM.
Regards ...

**Comment by Patsjemoe** [comment]
Hi Kallemanni,
Thank you for your quick suggestions.
Have already version 1.0.6....
Tried ESP32 Dev. Module, but also not working.
It just does not connect to the module. Tried different settings, nothing
works.
If anyone has other suggestions, they are also welcome.
Best regards
Ludo

**Comment by Patsjemoe** [comment]
Hi,
SOLVED 
Needed settings according attachmen
![image](https://user-images.githubusercontent.com/51908646/143870637-990931e2-b3d2-4ed4-a691-e943fb65a823.png)
t :
