### ISSUE TITLE
Add save to SD card and save to ftp server

### ISSUE THREAD

**Issue by zvegelj** [easytarget/esp32-cam-webserver#193]
It would be nice to have an option to save to SD card, and also to have an option to upload to FTP.  I think there are couple of projects which have this functionality, probably just need to integrate it.
One option is to have files on SD visible via http, so you could pull them from the serverside, automatically.
Not sure if it's possible to do "capture photo on movement detection" without motion sensor?

**Comment by easytarget** [comment]
#37
