### ISSUE TITLE
Add ESPOTA-server integration

### ISSUE THREAD

**Issue by skorokithakis** [easytarget/esp32-cam-webserver#211]
Hello! Would it be possible to use [ESPOTA-server](https://gitlab.com/stavros/espota-server) (and/or the [Arduino HTTP update library](https://github.com/esp8266/Arduino/blob/master/doc/ota_updates/readme.rst#advanced-updater)) for automatic pull-based updates? That would be very handy for automatically updating multiple devices on startup.

**Comment by easytarget** [comment]
No, no plans at all. It's not really appropriate for an example sketch like this.
