### ISSUE TITLE
error: 'struct camera_config_t' has no member named 'grab_mode'

### ISSUE THREAD

**Issue by TungstenE2** [easytarget/esp32-cam-webserver#215]
Just tried to update to 4.0 beta 3

Arduino: 1.8.19 (Windows 10), Board: "ESP32 Dev Module, Enabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, None"

C:\Users\xxx\Documents\Arduino\esp32-cam-webserver\esp32-cam-webserver.ino: In function 'void setup()':
esp32-cam-webserver:529:12: error: 'struct camera_config_t' has no member named 'grab_mode'
     config.grab_mode = CAMERA_GRAB_LATEST;
            ^
esp32-cam-webserver:529:24: error: 'CAMERA_GRAB_LATEST' was not declared in this scope
     config.grab_mode = CAMERA_GRAB_LATEST;
                        ^
Mehrere Bibliotheken wurden für "WiFi.h" gefunden
 Benutzt: C:\Users\xxx\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\libraries\WiFi
 Nicht benutzt: C:\Program Files (x86)\Arduino\libraries\WiFi
exit status 1
'struct camera_config_t' has no member named 'grab_mode'

![grafik](https://user-images.githubusercontent.com/39955685/153019000-aed89da3-1a38-4c5f-b46a-4ce48deb1ce4.png)

What is wrong?

**Comment by easytarget** [comment]
> Benutzt: C:\Users\xxx\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\libraries\WiFi
You are using v1.0.6 of the ESP ide. But 4.x only supports the latest ESP IDE Core version (v2.0.2)

**Comment by TungstenE2** [comment]
thx, but according to Arduino I have the latest version installed... hm

![grafik](https://user-images.githubusercontent.com/39955685/153138872-35723ffd-47e0-487f-a0b7-441e35ddc7e9.png)

**Comment by TungstenE2** [comment]
hm, uploaded now several times via OTA (some failed) and rebooted, but Cam module is not loading.

![grafik](https://user-images.githubusercontent.com/39955685/153146321-097f2cfb-05a2-4fcc-9251-21dd6115e578.png)
