### ISSUE TITLE
Spiffs: No filesystem found

### ISSUE THREAD

**Issue by TungstenE2** [easytarget/esp32-cam-webserver#216]
Just tried to update to the latest version.

Cam modul fails to load.

Board settings are according to docu.

![grafik](https://user-images.githubusercontent.com/39955685/153158056-5cd382b7-808c-48c4-bb98-8dbbefd14561.png)

![grafik](https://user-images.githubusercontent.com/39955685/153158195-9eeca168-59d2-42ab-a664-4140d8544360.png)

What is wrong?

**Comment by nassauwinter** [comment]
@TungstenE2 It seems to be related with #214. Got "SPIFFS: no filesystem found" error too.

**Comment by TungstenE2** [comment]
@easytarget could you please look into this? thx a lot

**Comment by TungstenE2** [comment]
this did the trick also for me:

The two steps:

    - flash SPIFFS_Test.ino from esp32 sketch example library
    - flash esp32-cam-webserver.ino

Cam modul is loading and stream and still is working again. Only dump page is not loading...


https://github.com/easytarget/esp32-cam-webserver/issues/214#issuecomment-1038100057

**Comment by easytarget** [comment]
Rolling this and all related into a single issue: #214
