### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by Fiore992** [easytarget/esp32-cam-webserver#219]
hi i am new to github and my english is bad so please forgive me but i had some problems in following your step to program. i have some problems: first i am confused in how to compile myconfig.h, has that to be a txt file? and what points have to be changed? i only changed ssid and password of ssid.
second when i go in settings, working on esp32-cam-webserver on arduino ide i can t find the networks port" i only wiew serial ports like com 1 and 3. how do i visualize that?
i have the esp32cam with the board above it with microusb connection. thanks if you can solve my problems and thanks a lot for your work

**Comment by easytarget** [comment]
copy the `myconfig.sample.h` file to `myconfig.h`, edit that in the arduino ide (or any other text editor), this is where you specify your Wifi details.
`myconfig.h` will be compiled when you 'upload' the sketch in the IDE.
The IDE shows you the USB devices connected; so plug in the board and select it then upload the sketch.
