### ISSUE TITLE
ESP32 Cam

### ISSUE THREAD

**Issue by Seveniur** [easytarget/esp32-cam-webserver#220]
Não consigo obter imagem só um borrão sem qq definição
![captureESP32CAM](https://user-images.githubusercontent.com/18468816/155121902-aaf42e67-af77-47a8-b7bf-1c4b50431b82.jpg)
.

**Comment by easytarget** [comment]
Engels of Nederlands, aub. 

But:
https://translate.google.com/?sl=auto&tl=en&text=N%C3%A3o%20consigo%20obter%20imagem%20s%C3%B3%20um%20borr%C3%A3o%20sem%20qq%20defini%C3%A7%C3%A3o&op=translate

Your camera module is not talking properly to the esp32 chip, this is common with budget modules.

Try reducing the frame size and resolution in the web interface, if that fails you can also try reducing the xclock frequency in myconfg.h
