### ISSUE TITLE
HELP WITH INO CODE

### ISSUE THREAD

**Issue by nandu-vnr** [easytarget/esp32-cam-webserver#254]
Iam getting error as below

C:\Users\itcore\Downloads\esp32-cam-webserver-master\esp32-cam-webserver-master\esp32-cam-webserver\esp32-cam-webserver.ino: In function 'void StartCamera()':
esp32-cam-webserver:341:12: error: 'struct camera_config_t' has no member named 'fb_location'
     config.fb_location = CAMERA_FB_IN_PSRAM;
            ^
esp32-cam-webserver:341:26: error: 'CAMERA_FB_IN_PSRAM' was not declared in this scope
     config.fb_location = CAMERA_FB_IN_PSRAM;
                          ^
esp32-cam-webserver:343:12: error: 'struct camera_config_t' has no member named 'grab_mode'
     config.grab_mode = CAMERA_GRAB_LATEST;
            ^
esp32-cam-webserver:343:24: error: 'CAMERA_GRAB_LATEST' was not declared in this scope
     config.grab_mode = CAMERA_GRAB_LATEST;

exit status 1
'struct camera_config_t' has no member named 'fb_location'

"I HAVE UPDATED MY IDE AND BOARDS AS WELL " but still I am getting this error . Please help me

**Comment by easytarget** [comment]
Please see #209 

You need at esp32 boards at version 2.0.2 or above. Double-check the boards URL is as listed in the answer above and in the README, many online guides give an obsolete URL for this.
