### ISSUE TITLE
sensor_t {aka struct _sensor}' has no member named 'set_xclk

### ISSUE THREAD

**Issue by OberfragGER** [easytarget/esp32-cam-webserver#261]
Hi,
i set the board to ESP32Dev Modlue, set the right partition sheme like mentioned and als the PSRAM. But i geht the error on compile. Whats wrong or how to fix it?

`Arduino: 1.8.19 (Windows 10), Board: "ESP32 Dev Module, Enabled, Minimal SPIFFS (1.9MB APP with OTA/190KB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, None"

...\Arduino\esp32-cam-webserver\storage.cpp: In function 'void loadPrefs(fs::FS&)':

storage.cpp:107:8: error: 'sensor_t {aka struct _sensor}' has no member named 'set_xclk'

     s->set_xclk(s, LEDC_TIMER_0, xclk);

        ^

...\Arduino\esp32-cam-webserver\esp32-cam-webserver.ino: In function 'void StartCamera()':

esp32-cam-webserver:341:12: error: 'struct camera_config_t' has no member named 'fb_location'

     config.fb_location = CAMERA_FB_IN_PSRAM;

            ^

esp32-cam-webserver:341:26: error: 'CAMERA_FB_IN_PSRAM' was not declared in this scope

     config.fb_location = CAMERA_FB_IN_PSRAM;

                          ^

esp32-cam-webserver:343:12: error: 'struct camera_config_t' has no member named 'grab_mode'

     config.grab_mode = CAMERA_GRAB_LATEST;

            ^

esp32-cam-webserver:343:24: error: 'CAMERA_GRAB_LATEST' was not declared in this scope

     config.grab_mode = CAMERA_GRAB_LATEST;

                        ^

...\Arduino\esp32-cam-webserver\app_httpd.cpp: In function 'esp_err_t cmd_handler(httpd_req_t*)':

app_httpd.cpp:366:63: error: 'sensor_t {aka struct _sensor}' has no member named 'set_xclk'

     else if(!strcmp(variable, "xclk")) { xclk = val; res = s->set_xclk(s, LEDC_TIMER_0, val); }

                                                               ^

Mehrere Bibliotheken wurden für "WiFi.h" gefunden

 Benutzt: ...\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.2\libraries\WiFi

 Nicht benutzt: C:\Program Files (x86)\Arduino\libraries\WiFi

exit status 1

'sensor_t {aka struct _sensor}' has no member named 'set_xclk'`

**Comment by sonofcy** [comment]
Set the board to esp32cam, usually an AI-THINKER board.

**Comment by OberfragGER** [comment]
Same error. I also dont have any Option to set the PSRAM, partitions e.g.

Its a fresh install with newest ArduinoIDE.

The compiling of the example code throws no error.

which version of the board-preference should i choose and is working? I use 1.0.2. With the newest 1.0.6 its not compiling the example.

**Comment by sonofcy** [comment]
Current version is 2.0.3 last time I checked, but the old esp32cam-webserver will not compile, you have to revert the board to 1.0.6. There is a v4 I think of the webserver somewhere, it is the latest, this is old and they messed it up.

**Comment by OberfragGER** [comment]
I installed the newest Arduino IDE (2.0.0-rc9) and also the newest Boardmanager.
Just edited the myconfig.h and set the "Arduino Dev Module" like descibed.

Works now. Thanks a lot.
