### ISSUE TITLE
Feature Request: Auto reboot

### ISSUE THREAD

**Issue by TungstenE2** [easytarget/esp32-cam-webserver#266]
Hi all,

I have a cam at my door, which is not responding after some days in operation. A second cam with same fw is working fine for several weeks.

So I was wondering if there is an option to reboot the cam very night at a specific time?

Either by code enhacement or by external http comand.

thx

**Comment by TungstenE2** [comment]
@easytarget  push ;-)

**Comment by abratchik** [comment]
@TungstenE2 I think you can use the `http://<your-ip:your-port>/cmdout?var=reboot&val=1` command. You can also trigger it by a schedule with help of any external tool.

**Comment by easytarget** [comment]
Sorry; I am not doing any further development on this project. it is old code and somewhat obsolete. I am currently working on retiring it; I will try to link to a more actively updated fork when I do.
