### ISSUE TITLE
Newbie Question

### ISSUE THREAD

**Issue by BoraSchninsky** [easytarget/esp32-cam-webserver#267]
When i use this script i become a red error in this  declaration ----- _struct station stationList[] = {{"Wifi","12345", true}};_   ------
"stationList" is with red underline in VBCode

Please help me!

other question ..
can i make a camera server and a mesh repeater with "painless" library in on project?
This saves a second hardware

please help me!

Thanks from Germany

**Comment by easytarget** [comment]
Sorry; I am not doing any further development on this project. it is old code and somewhat obsolete. I am currently working on retiring it; I will try to link to a more actively updated fork when I do.
