### ISSUE TITLE
is it posble to add mqtt?

### ISSUE THREAD

**Issue by FedericoSebas** [easytarget/esp32-cam-webserver#271]
it's for moving a car, it only needs to subscribe. i've been trying to do it by myself but is hard.

**Comment by easytarget** [comment]
A good idea ;but I'm afraid I was not able to look at it.
Sorry; I am not doing any further development on this project. it is old code and somewhat obsolete. I am currently working on retiring it; I will try to link to a more actively updated fork when I do.
