### ISSUE TITLE
Not able to change AP details

### ISSUE THREAD

**Issue by Alfrs28** [easytarget/esp32-cam-webserver#272]
I am not able to change the accesspoint details. I tried to change all the necessary parts of the myconfig.sample.h file and saved it as myconfig.h. unfortunately it still uses the default details. can someone give me a hint which part I have to change to just use the same IP and everything as in the default but my own AP name and password?
Thanks

**Comment by easytarget** [comment]
Sorry; I am not doing any further development on this project. it is old code and somewhat obsolete. I am currently working on retiring it; I will try to link to a more actively updated fork when I do.
