### ISSUE TITLE
src/parsebytes.h: No such file or directory

### ISSUE THREAD

**Issue by sbx59** [easytarget/esp32-cam-webserver#276]
hello, 
I just followed the tutorial, but I have two errors. Can you help me ?

Plusieurs bibliothèque trouvées pour "WiFi.h"
esp32-cam-webserver:8:10: fatal error: src/parsebytes.h: No such file or directory
Utilisé : C:\Users\USER\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.5\libraries\WiFi
 #include "src/parsebytes.h"
Non utilisé : C:\Program Files (x86)\Arduino\libraries\WiFi
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
src/parsebytes.h: No such file or directory

![esp32](https://user-images.githubusercontent.com/78600632/202165942-b8e4ea6f-6d54-4846-bf2b-6284540cc6e3.png)

**Comment by sbx59** [comment]
for wifi it's good, just delete the folder in question. On the other hand, for the parsebytes file how to do? he is present!

**Comment by MavricFloquet** [comment]
Hello, i have the same probleme do you have any issu ? THX

**Comment by sonofcy** [comment]
What tutorial? Just download the zip, rename from esp32-cam-webserver-master to esp32-cam-webserver. Unzip, follow instructions re ssid and password, compile the main ino file. I have several cameras running this software.

**Comment by sbx59** [comment]
Good for me now .

**Comment by sonofcy** [comment]
Since the error is "src/parsebytes.h" we know there has to be a src directory in your sketch directory. Here is what my dir structure looks like.
<img width="545" alt="Screenshot 2022-11-29 at 12 49 35" src="https://user-images.githubusercontent.com/45547504/204644693-da57c66d-8487-41f8-adf2-d4af8bf54e51.png">

**Comment by sore-ron-git** [comment]
Issue occurs when you rename the zip file from esp32-cam-webserver-master.zip to esp32-cam-webserver.zip.

When you extract this file it creates esp32-cam-webserver-master folder.

You need to rename this folder as well to esp32-cam-webserver

**Comment by easytarget** [comment]
Sorry; I am not doing any further development on this project. it is old code and somewhat obsolete. I am currently working on retiring it; I will try to link to a more actively updated fork when I do.
