### ISSUE TITLE
L2TP / IPsec

### ISSUE THREAD

**Issue by Magura94** [easytarget/esp32-cam-webserver#277]
Hello, 

is it possible to configure the esp32 as a vpn tunnel with l2tp/ IPSec?

**Comment by sonofcy** [comment]
I believe those are software related not hardware so it's really an esp32 issue.

**Comment by easytarget** [comment]
Sorry; I am not doing any further development on this project. it is old code and somewhat obsolete. I am currently working on retiring it; I will try to link to a more actively updated fork when I do.
