### ISSUE TITLE
Why not use WiFiManager?

### ISSUE THREAD

**Issue by sonofcy** [easytarget/esp32-cam-webserver#279]
Wouldn't it make sense to add something like the WiFiManager library to this project? It would eliminate a lot of code and simplify the WiFi portion of the code. There are many versions but the one I use and I think is the original is at 
https://github.com/tzapu/WiFiManager

**Comment by easytarget** [comment]
Sorry; I am not doing any further development on this project. it is old code and somewhat obsolete. I am currently working on retiring it; I will try to link to a more actively updated fork when I do.
