### ISSUE TITLE
Shifted Pixel Rows and Columns

### ISSUE THREAD

**Issue by mmatthe** [easytarget/esp32-cam-webserver#281]
thanks for the great project! I use it to make still images of my gas meter, to process later on. Unfortunately, it occurs randomly (like 5% of the taken photos) that the rows and columns are shifted by a few pixels, like here (I pixelated sensitive information):

![image](https://user-images.githubusercontent.com/16668802/207811905-69d8f6ed-d8cb-4d2c-a660-b5e35904121d.png)

On the right side of the image, there is a strong edge to be seen, and it occurs that these columns should actually belong to the left side of the image. But, does not happen for the upper X rows. 

The image is taken via the /capture endpoint, and the stream is switched off. I also attach the configuration. 
![image](https://user-images.githubusercontent.com/16668802/207812425-311d3b1d-675d-45b5-afc5-4938b41f796f.png)

is there something that can be done against these shifts?

**Comment by easytarget** [comment]
Sorry; I am not doing any further development on this project. it is old code and somewhat obsolete. I am currently working on retiring it; I will try to link to a more actively updated fork when I do.
