### ISSUE TITLE
camera config fails but camera runs other example correctly

### ISSUE THREAD

**Issue by ne9n** [easytarget/esp32-cam-webserver#288]
I want to use this app as it has some features I need.  The sample code works but this one fails on camera config

===
esp32-cam-webserver: EnderCamWeb
Code Built: Feb 16 2023 @ 18:27:38
Base Release: 4.0

E (581) cam_hal: cam_dma_config(306): frame buffer malloc failed
E (581) cam_hal: cam_config(390): cam_dma_config failed
E (581) camera: Camera config failed with error 0xffffffff

CRITICAL FAILURE: Camera sensor failed to initialise.

A full (hard, power off/on) reboot will probably be needed to recover from this.
Meanwhile; this unit will reboot in 1 minute since these errors sometime clear automatically
No Internal Filesystem, cannot load or save preferences

dump
E (67958) task_wdt: CPU 0: IDLE
E (67958) task_wdt: CPU 1: IDLE
E (67958) task_wdt: Aborting.

abort() was called at PC 0x400e7a21 on core 0

Backtrace: 0x40083b75:0x3ffc052c |<-CORRUPTED

ELF file SHA256: 170467b9b884d009

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13836
load:0x40080400,len:3608
entry 0x400805f0

**Comment by easytarget** [comment]
Sorry; I am not doing any further development on this project. it is old code and somewhat obsolete. I am currently working on retiring it; I will try to link to a more actively updated fork when I do.
