### ISSUE TITLE
OV5640

### ISSUE THREAD

**Issue by apapapapapapap** [easytarget/esp32-cam-webserver#291]
When connecting a OV5640 lens module i get the following message:
--------------------------------------------------------
Camera init succeeded
WARNING: Camera module is unknown and not properly supported, will fallback to OV2640 operation
--------------------------------------------------------

Tried 3 different OV5640 modules. 2 don't showed any picture at all, one was working as a OV2640 (max. 1600 * 1200).

**Comment by meltoner** [comment]
had no issues though didn't push it at its highest resolution as i am going for the better sensor and not for higher resoltution

**Comment by easytarget** [comment]
Sorry; I am not doing any further development on this project. it is old code and somewhat obsolete. I am currently working on retiring it; I will try to link to a more actively updated fork when I do.
