### ISSUE TITLE
started getting this

### ISSUE THREAD

**Issue by lohtse** [easytarget/esp32-cam-webserver#300]
esp32-cam-webserver:2:10: fatal error: esp_int_wdt.h: No such file or directory
    2 | #include <esp_int_wdt.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
exit status 1
esp_int_wdt.h: No such file or directory

As you can see above.

I have flashed a dozen or more Cams over the past years or two.... got a could of new ones and cannot get best the above error...

any ideas what to do next?

**Comment by SchneHa** [comment]
Maybe it's of a newer board definition. Try 2.0.X

Edit: 2.0.2 worked for me!

**Comment by diramazioni** [comment]
@SchneHa do you mean arduino 2.0.X? I can't get to work with it, I've the same issue

**Comment by SchneHa** [comment]
No, I mean board version 2.0.2.

**Comment by diramazioni** [comment]
Dear @SchneHa sorry but don't know for sure what you are referring to: 
some background info: I'm trying out with the [ESP32_S3_WROOM_Board](https://github.com/Freenove/Freenove_ESP32_S3_WROOM_Board) the provided webserver example has [define CAMERA_MODEL_ESP32S3_EYE](https://github.com/Freenove/Freenove_ESP32_S3_WROOM_Board/blob/05388d3ab045db4336c915482e185e4c4d77aaa1/C/Sketches/Sketch_07.1_CameraWebServer/Sketch_07.1_CameraWebServer.ino#L15) as boards pin. 
[I'm a bit lost](https://github.com/Freenove/Freenove_ESP32_S3_WROOM_Board/issues/6) in what board to use and the only one that I found working is the `esp32s3usbotg` but I'm not sure is the correct one.
I've even installed the esp-idf board definitions

**Comment by SchneHa** [comment]
Are you using Arduino IDE? Go to board manager and check what esp32 board version is installed. Maybe you have to choose an older version.

**Comment by easytarget** [comment]
Sorry; I am not doing any further development on this project. it is old code and somewhat obsolete. I am currently working on retiring it; I will try to link to a more actively updated fork when I do.
