### ISSUE TITLE
ssid issue

### ISSUE THREAD

**Issue by Uzziza** [easytarget/esp32-cam-webserver#303]
My SSID name is XXXXX-XX, when having the - in the name the ESP32 Cam never connects to the wifi.

Renaming the SSID to XXXXX fixes the issue, can this be fixed?

**Comment by easytarget** [comment]
Sorry; I am not doing any further development on this. it is old code and somewhat obsolete. I am currently working on retiring it; I will try to link to a more actively updated fork when I do.
