### ISSUE TITLE
init error

### ISSUE THREAD

**Issue by Ekac00** [easytarget/esp32-cam-webserver#304]
en:
There is an issue with camera initialization. Can we skip initialization or cancel camera occupation before the program runs?
cn:
相机初始化有问题，能不能跳过初始化或在程序运行前取消相机占用？
jp:
カメラの初期化に問題があります。初期化をスキップしたり、プログラムの実行前にカメラ占有をキャンセルしたりすることはできますか？

**Comment by easytarget** [comment]
Sorry; I am not doing any further development on this. it is old code and somewhat obsolete. I am currently working on retiring it; I will try to link to a more actively updated fork when I do.
