### ISSUE TITLE
Custom hostname not working

### ISSUE THREAD

**Issue by Nikishek** [easytarget/esp32-cam-webserver#309]
Whatever hostname I set, I still get a hostname in the format "esp32-[MAC]". 
A quick solution or rather workaround is to put WiFi.setHostname(mdnsName); at the beginning of the WifiSetup() or setup().
How should it be done properly?

There is also another unrelated problem that the custom URL_HOSTNAME doesn't work. I guess it's probably more of a problem on my router.

**Comment by easytarget** [comment]
Sorry; I am not doing any further development on this. it is old code and somewhat obsolete. I am currently working on retiring it; I will try to link to a more actively updated fork when I do.
