### ISSUE TITLE
how to get working with ov2640

### ISSUE THREAD

**Issue by cozmo14047** [easytarget/esp32-cam-webserver#311]
hi there how can i get this working with the ov2640 camera

**Comment by cozmo14047** [comment]
I figured it out you have to change the pin definition for the ai thinker board if you use alixpress clones

**Comment by tobiasisenberg** [comment]
But how specifically? Can you provide details or a link to the respective resource?

**Comment by cozmo14047** [comment]
> But how specifically? Can you provide details or a link to the respective resource?




Jeez, it's been a while since I got this working—I completely forgot about this thread, lol. Do you have Discord? It'd be easier to help you there. There wasn't a single resource; it involved a lot of digging through schematics, source code, etc.

**Comment by tobiasisenberg** [comment]
My hunch now is that my own camera is somehow broken, as it used to work before and now does not work with 2 ESP32-CAM modules in which other cameras work. Nonetheless, I found several different pinouts online, but mostly for other modules with a USB-C connector, not the plain ESP32-CAM modules w/o USB connector. But if you still have your code somewhere it may be worth it to post your own changed pin assignment, so that others can compare it to theirs.

**Comment by cozmo14047** [comment]
> My hunch now is that my own camera is somehow broken, as it used to work before and now does not work with 2 ESP32-CAM modules in which other cameras work. Nonetheless, I found several different pinouts online, but mostly for other modules with a USB-C connector, not the plain ESP32-CAM modules w/o USB connector. But if you still have your code somewhere it may be worth it to post your own changed pin assignment, so that others can compare it to theirs.



It could be broken, but that's unlikely unless the ribbon cable is damaged. If I find it, I'll upload it somewhere, though it's probably buried deep in my hard drive. So, do you only have the camera module and not the programming board? If that's the case, you'll need an Arduino or another AVR programmer to program them, I believe.

**Comment by tobiasisenberg** [comment]
I do have the programming board, And a new camera module is on the way. I am pretty confident it is the camera.

**Comment by cozmo14047** [comment]
> I do have the programming board, And a new camera module is on the way. I am pretty confident it is the camera.

Ok let me know if it still doesnt work and ill find the code

**Comment by tobiasisenberg** [comment]
It was the camera: it works fine with a new one. So all is good now on my side. Nonetheless, if you come across the changed config it would be nice to have a link here or the actual pin numbers that need to change.

**Comment by cozmo14047** [comment]
> It was the camera: it works fine with a new one. So all is good now on my side. Nonetheless, if you come across the changed config it would be nice to have a link here or the actual pin numbers that need to change.

Thats good that its working now, is there a chance it could be the pins on the other camera are just diffrent? Yeah ive been looking im pretty sure i know know where the config is if so ill make a pull request here to add the option

**Comment by easytarget** [comment]
Sorry; I am not doing any further development on this. it is old code and somewhat obsolete. I am currently working on retiring it; I will try to link to a more actively updated fork when I do.
