### ISSUE TITLE
Streaming on Andorid Phone not possible

### ISSUE THREAD

**Issue by JoJos1220** [easytarget/esp32-cam-webserver#312]
As descriped in the title, it is not possible in the simple/full mode by activating start stream to get a stream view. It works in Browser (Firefox) perfectly as excepted but the stream does not work on Android.

The Get still button gives a screen but no moving stream.

**Comment by JoJos1220** [comment]
As a Breakpoint:

the issue occurs if the URL_HOSTNAME & the MCNS_NAME was activated and setted up exactly the same string. Maybe this is a helpful information

**Comment by easytarget** [comment]
Sorry; I am not doing any further development on this. it is old code and somewhat obsolete. I am currently working on retiring it; I will try to link to a more actively updated fork when I do.

**Comment by JoJos1220** [comment]
I understand that the developement of the repository is then ongoing on an other thread or another repository. But I think, the issue is NOT closed then until it is solved within another aspect....

**Comment by easytarget** [comment]
It is, however, closed for this repository. 
In any case this sounds like a issue with the browser on your phone, not with the cam server itself.
