### ISSUE TITLE
Start Recording and led on off issues

### ISSUE THREAD

**Issue by Chandzaib** [easytarget/esp32-cam-webserver#314]
I have this sp32 camera i have loaded the code trap into it it is working as a web server with my wifi and is showing video and streaming but its not working Recording start and on led on off option

**Comment by cor-of-org** [comment]
Do you have a question? 

If so, ask it. Also, provide full system/script/debug information along with your question.

As it stands, you have exactly zero chance of getting a useful answer.

**Comment by easytarget** [comment]
Sorry; I am not doing any further development on this. it is old code and somewhat obsolete. I am currently working on retiring it; I will try to link to a more actively updated fork when I do.
