### ISSUE TITLE
Stream Window is not rotated on port 81

### ISSUE THREAD

**Issue by normvp** [easytarget/esp32-cam-webserver#315]
I am finding that I can easily and properly rotate the image in browser using port 80, while I am configuring the ESP32_Cam_Webserver, however, The stream that I want to watch on port 81 is not rotated.  I can flip back and forth between two open tabs for the ESP32-Cam and see correctly rotated on port 80 and ignoring the rotation setting on port 81.  This puzzles me because I can temporarily see the rotated stream on port 80.  Do I misunderstand what the steam should be capable of, or is there a bug with rotating the stream on port 81?

**Comment by easytarget** [comment]
That is correct. The stream itself cannot be rotated (a hardware limit) so the rotation is applied in the web browser via a CSS setting in the browser.

Implementing rotation (which has to be done like this) is the original reason I started this project. Adding light control was the second thing I did..

But anyway, I am sorry but I am not doing any further development on this. it is old code and somewhat obsolete. I am currently working on retiring it; I will try to link to a more actively updated fork when I do.
