### ISSUE TITLE
Sending data to Serial2 from the video stream.

### ISSUE THREAD

**Issue by arobosa1** [easytarget/esp32-cam-webserver#317]
I have a barcode scanner connected to UART2. Serial2 is initialized in the program. The output from Serial2 is redirected to the main console (Serial). When I enable the video stream, some data keeps coming in there all the time. What could be causing this, and how can I disable it?

**Comment by easytarget** [comment]
Sorry; I am not doing any further development on this. it is old code and somewhat obsolete. I am currently working on retiring it; I will try to link to a more actively updated fork when I do.
