### ISSUE TITLE
Compiling needs older board version

### ISSUE THREAD

**Issue by ClearlyDazed** [easytarget/esp32-cam-webserver#320]
Ver 4.0 compiles using ESP32 Dev Module ver 2.0.17

**Comment by easytarget** [comment]
yes. This code is not compatible with any ESP version from v2.1 onwards.

Sorry; I am not doing any further development on this. it is old code and somewhat obsolete. I am currently working on retiring it; I will try to link to a more actively updated fork when I do.

**Comment by ClearlyDazed** [comment]
@easytarget Thanks for this app. With this being its EOL, should it still work if compiled with the correct version. I am asking since the camera is no longer working. What would cause this?
