### ISSUE TITLE
CNN location issue.

### ISSUE THREAD

**Issue by Anonymus-arch** [easytarget/esp32-cam-webserver#321]
How can i add a condition to the cnn to be runned like if a specific gpio is in High state then only the cnn runs and also the cameraServer. If this happens users can easily disable and enable the cameraserver and face detection making esp32 cam to save more energy. If you are unable to make a code for new ENERGY SAVING Code then at least please send the block where the cnn starts.
Regards,
            Pranjal Prabhat
Thank You

**Comment by easytarget** [comment]
Sorry; I am not doing any further development on this. it is old code and somewhat obsolete. I am currently working on retiring it; I will try to link to a more actively updated fork when I do.
