### ISSUE TITLE
NTP client sync for RTC

### ISSUE THREAD

**Issue by easytarget** [easytarget/esp32-cam-webserver#38]
Enable the RTC in the esp32  so that we can use the system time effectively.
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/system_time.html

And select a time source: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/system_time.html#rtc-clock-source
(the 8.5MHz option makes sense, we dont need to save power in deep sleep modes for this project)

* Useful in V4 for saving files to disk, putting a timestamp on face detection events, logging, etc.
* Provide a global flag that can be set to say 'NTP synced', and chose file names sensibly depending on that.
* This looks like a good candidate: https://github.com/arduino-libraries/NTPClient
* Config: activate by defining a ntp pool server in myconfig.h

**Comment by TungstenE2** [comment]
also option to use DST would be nice. 

![grafik](https://user-images.githubusercontent.com/39955685/94466907-74375a80-01c2-11eb-8f2a-aeb1e7f976ea.png)
