### ISSUE TITLE
video stream using tinyCam PRO is not working

### ISSUE THREAD

**Issue by TungstenE2** [easytarget/esp32-cam-webserver#57]
Hi, 

when I used the original demo version available in Arduino IDE I was able to get the video stream on my mobile using tinyCam PRO Android app. 

Settings:
Vendor: Generic
Camera model: Generic URL
URL: http://IP:81/stream
Protocol: snapshot (JPEG)

Now with your project the above settings (but URL http://IP:81/view) does not show the stream.

Also changing the protocol to 'Server push (MJPEG)' does not work.

![grafik](https://user-images.githubusercontent.com/39955685/94475747-d185d880-01cf-11eb-80a5-7fb0e09c36f5.png)
![grafik](https://user-images.githubusercontent.com/39955685/94475769-d8ace680-01cf-11eb-8d2a-486db0a77c10.png)

Any ideas?

Thx

**Comment by easytarget** [comment]
Remove the `view` part of the url, eg `http//IP:81/`
the stream itself is on the raw port, the `/view` URL is for the html page of the stream viewer

**Comment by TungstenE2** [comment]
great, this worked!

May be it would worth to have a URL chapter on the project info page, listing the most common once:

eg:
GUI for settings
http://"IP"/

Snapshot
http://"IP"/capture

Stream in html page
http://"IP":81/view

raw stream for survillance clients
http://"IP":81/

commands:
Flash light: on/off
http://"IP"/control?var=lamp&val=100
http://"IP"/control?var=lamp&val=0

etc...

**Comment by easytarget** [comment]
That is why I created #55 :wink:
