### ISSUE TITLE
Components-Object deprecated and to be removed

### ISSUE THREAD

**Issue by TungstenE2** [easytarget/esp32-cam-webserver#61]
I am getting a warning in Firefox developer tools about deprecated Components-Object still used.
It should no longer be used.

'Das Components-Objekt sollte nicht mehr verwendet werden. Es wird bald entfernt.'

![grafik](https://user-images.githubusercontent.com/39955685/94672669-dc4a8580-0315-11eb-8586-0ae7e20d231f.png)

**Comment by easytarget** [comment]
Humm, curious.
Which FFox version are you using; and what OS (Win/Linux?) 

I dont see any depreciation warnings, nor any of the CSS warnings. I'm on Fedora32 and update daily. I just double-checked and have a clean log on FFox 81.0, Chromium 85.0.4183.102, Chrome 86.0.4240.53 and Chrome(unstable) 87.0.4270.0

**Comment by TungstenE2** [comment]
using FF 81.0 64-Bit on Windows 10

currently using 2 cams, same build date, but differnt lenses.
Both have the warnings.

![grafik](https://user-images.githubusercontent.com/39955685/94784024-d57f4980-03cd-11eb-8b7a-4f7d503d53ed.png)

**Comment by easytarget** [comment]
Thankyou, I'll reboot into windows later and see if I can reproduce,

**Comment by easytarget** [comment]
I do not see this (Win10, ffox 81), nor in edge etc.. Looking at the error I noticed it is *not* referencing the html or css, but is attached to the IP address itself

On my system I see:
![no-depreciated-objects](https://user-images.githubusercontent.com/4005142/95000437-23a86e80-05c1-11eb-8b71-62e7e7b47434.png)
I get the other warnings about pseudo-classes etc (they will be fixed), but the big scary depreciation notice is absent.

I'm guessing this is something specific to your browser extensions, I found this:
https://stackoverflow.com/questions/59107409/what-to-do-about-the-components-object-is-deprecated-it-will-soon-be-removed

Closing for now.
