### ISSUE TITLE
V.3 announcement: is it faster?

### ISSUE THREAD

**Issue by ozett** [easytarget/esp32-cam-webserver#65]
hi, today i tried your code, 
now i just got the v3. announcment a minute ago.

my impression was before, your code is a bit slower than the general cam-example-code.

i did not find any hints, that there had been speed improvements in V3... 
Or was my impression wrong?

thx.

**Comment by easytarget** [comment]
The streaming code is untouched. If the stream is faster/slower that is due to your network, browser, etc.
Speed is not an issue, nothing has changed, nothing needs to change.
