### ISSUE TITLE
V3 ++ Versioning?

### ISSUE THREAD

**Issue by ozett** [easytarget/esp32-cam-webserver#67]
i try V3beta3, and before the github version.
How do i differentiate the code-base/versions?
maybe even if it is flashed in different versions on different boards?

when the board dont get a webgui ready,
 it would be great to see the version on the serial-monitor..

**Comment by ozett** [comment]
i think i found it 
(on the old github version, because no reboots like in v3beta3)

where can i check it in the source? i made several folders with versions, i cannot see on the folder which is which..

![image](https://user-images.githubusercontent.com/5937811/95204850-ed4b3900-07e4-11eb-8590-c2d24e2e8bec.png)

**Comment by easytarget** [comment]
The best I can (automatically) provide is the build time that you found. And this is not recorded in the code, it is added when you compile it.

I'll think about adding a version to the code; but I'll have to remember to update this myself or set up some complicated scripting on my build machine(s). Yet one more thing to maintain/go wrong... :frowning_face: but you are correct in that it would be a useful thing to supply.
- Side step to rant about the ArduinoIDE/toolchan not including a git describe macro or similar...

Until then you'll need to keep track yourself of where you unpacked the releases. Sorry.

**Comment by ozett** [comment]
i played before with espeasy a lot https://github.com/letscontrolit/ESPEasy

may you have a look into their code?
they have a statuspage with somethin like `git-versioning`.. 

dont know how they do it, maybe an idea to investigate?
(still also not fully implemented versioning at their side)

![image](https://user-images.githubusercontent.com/5937811/95207751-7ca61b80-07e8-11eb-81a0-23013aee0cfa.png)

**Comment by easytarget** [comment]
And it is also trivial in platformio, VS, esp ide and any commandline tool.. 
However.. 
This project targets beginners and the Arduino IDE. Which has no equivalent. So it's not going to 'just happen'.

**Comment by easytarget** [comment]
Sorry if last reply was a bit terse; I've got a lot on.
But.. fundamentally a good suggestion, so I have added a version string (that I need to update manually) to the code and outputs.
