### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by projectsun2** [easytarget/esp32-cam-webserver#81]
What have I done wrong?

![compile](https://user-images.githubusercontent.com/39924182/98105746-a8282e80-1e98-11eb-9f65-d8edd52d1125.JPG)

**Comment by easytarget** [comment]
Looks like you do not have the correct version of the ESP32 libraries.
I only test/support building against the latest ESP32 libraries from https://dl.espressif.com/dl/package_esp32_index.json 
- Currently that is v1.0.4
![Screenshot from 2020-11-06 17-06-12](https://user-images.githubusercontent.com/4005142/98388544-31836080-2053-11eb-8db6-3ff0bd23dc42.png)

If you have a older version, upgrade..
If you got the ESP board via another method, or have modified the installed files in `.arduino15/packages/esp32/` you'll need to undo that (at least while you wish to compile this code..)

**Comment by projectsun2** [comment]
Issue can be closed: Yes, I had 1.0.1. Updating did the trick. Thank you.

**Comment by easytarget** [comment]
Glad you got it going. thanks for the feedback.
