### ISSUE TITLE
no stream possible anymore

### ISSUE THREAD

**Issue by TungstenE2** [easytarget/esp32-cam-webserver#85]
Hi,

I have 3 ESP32 cams, all operation with your webserver version.
Compiled Oct 26 2020 @ 12:42:11

One of my cams is acting strange for a couple of weeks.

Webserver is working.
Get Still is working but no streaming is possible.

Auto lamp is always switching on the LED, like as a stream is currently in progress, but I have checked all my devices and none is calling the stream.

Any idea how to fix this? Device is powered 24/7 in a 3D printed housing.

Thx

**Comment by TungstenE2** [comment]
Seems I found the reason in my network and could fix it.

But on the way I discovered that the webserver will only connect to channel 1 and ignores closer network with stronger signal and same SSID but using channel 6.

**Comment by buteomont** [comment]
> Seems I found the reason in my network and could fix it.

Care to elaborate? I'm having the same issue.  I can control the light, etc. and can take still snapshots but the streaming will not work.

**Comment by easytarget** [comment]
The stream happens on a different port number (port 81 by default); so I'm guessing it was a NAT/route/firewall issue somewhere along the line ;-) or possibly something even more gnarly and complicated.

If you still see an issue, try directly connecting to port 81 (the URL is in the serial startup dump) and see if this works.. 
- If you cant connect to it then you probably have a network issue and need to address that.
- If you connect but get no response have a look at the serial debug info, (send a 'd' in the console for a dump too) and start a new issue if you cant find any good answers online or in this issue tracker.

**Comment by buteomont** [comment]
Thanks.  I can get the stream on port 81 directly using VLC, Opera or 
Firefox, but the stream won't show up on the web page with the controls. 
Might be a CSS problem since I can never get mDNS to work on my network and 
I have to use the actual IP address in the URL. That's not a big deal but 
the frame rate is really slow, maybe one frame/second. Not sure if that is 
normal for this camera.
