### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by TungstenE2** [easytarget/esp32-cam-webserver#95]
Dear @easytarget,

could you may be update your documentation on best practise in order to use Aduino IDE for your project?

Not sure if I do the steps in the right order.

- I download the code as zip file from github
- export from zip file to folder on my PC
- open Arduino IDE (latest stable version 1.8.13)
- drag and drop files to Arduino IDE
![grafik](https://user-images.githubusercontent.com/39955685/110482974-8a3e3500-80e9-11eb-8962-1d0c8f9e66a1.png)
- edit myconfig.h
- compile and upload

But  by doing as above, I get a subfolder named 'esp32-cam-webserver' containing all the files duplicated.

![grafik](https://user-images.githubusercontent.com/39955685/110483275-db4e2900-80e9-11eb-8612-a1d54d779216.png)

So there should be a better way. Can you please share the supposed steps in your documentation?

https://github.com/easytarget/esp32-cam-webserver

![grafik](https://user-images.githubusercontent.com/39955685/110482480-fff5d100-80e8-11eb-8b39-f595d726bf11.png)

thx a lot in advance

**Comment by easytarget** [comment]
Sorry slow response, but thankyou for reporting this, it's good to have someone else reading stuff and feeding back. Even if I cant always fix things properly. 

I'll add some notes to the readme and the hackaday page.

In the past I dealt with this by repacking the tarballs, but I have a cunning plan for refactoring the V4 branch in a better way (one that I see other platformIO projects using).

**Comment by easytarget** [comment]
Fixed by commit 15018a5

**Comment by easytarget** [comment]
Fixed by commit 15018a5
