### ISSUE TITLE
http commands

### ISSUE THREAD

**Issue by TungstenE2** [easytarget/esp32-cam-webserver#96]
Hi @easytarget,

is it possible to change settings using http commands?

eg 'set lamp off' or 'set lamp 75%'

This would be very helpfull.

thx

**Comment by easytarget** [comment]
https://github.com/easytarget/esp32-cam-webserver/blob/master/API.md

Look at the examples at the end. This should provide all you need. I just made the examples a tad clearer.

**Comment by TungstenE2** [comment]
great, thx.

I would suggest to add this information as well to the project main page, so it is easy to find.
https://github.com/easytarget/esp32-cam-webserver

**Comment by TungstenE2** [comment]
push, please add link to main page.

https://github.com/easytarget/esp32-cam-webserver
